-- =====================================================
-- Oracle APEX - جداول قاعدة البيانات (نسخة مصححة)
-- =====================================================

-- 1️⃣ جدول التقارير الرئيسي
CREATE TABLE METAR_REPORTS (
    REPORT_ID NUMBER PRIMARY KEY,
    STATION_CODE VARCHAR2(10) NOT NULL,
    OBSERVATION_TIME TIMESTAMP NOT NULL,
    LATITUDE NUMBER(10,6),
    LONGITUDE NUMBER(10,6),
    TEMPERATURE NUMBER(5,2),
    DEW_POINT NUMBER(5,2),
    WIND_DIRECTION NUMBER(3),
    WIND_SPEED NUMBER(5,2),
    VISIBILITY NUMBER(10,2),
    PRESSURE NUMBER(10,2),
    WEATHER_CODES VARCHAR2(100),
    RAW_METAR VARCHAR2(500),
    NETWORK VARCHAR2(20),
    COUNTRY_CODE VARCHAR2(5),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_METAR UNIQUE (STATION_CODE, OBSERVATION_TIME)
);

-- إنشاء Sequence
CREATE SEQUENCE METAR_REPORTS_SEQ START WITH 1 INCREMENT BY 1;

-- إنشاء Indexes للأداء
CREATE INDEX IDX_METAR_STATION ON METAR_REPORTS(STATION_CODE);
CREATE INDEX IDX_METAR_TIME ON METAR_REPORTS(OBSERVATION_TIME);
CREATE INDEX IDX_METAR_WEATHER ON METAR_REPORTS(WEATHER_CODES);
CREATE INDEX IDX_METAR_COUNTRY ON METAR_REPORTS(COUNTRY_CODE);

-- =====================================================

-- 2️⃣ جدول الظواهر الغبارية
CREATE TABLE DUST_PHENOMENA (
    PHENOMENON_ID NUMBER PRIMARY KEY,
    REPORT_ID NUMBER NOT NULL,
    PHENOMENON_TYPE VARCHAR2(10) NOT NULL,
    SEVERITY VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_DUST_REPORT FOREIGN KEY (REPORT_ID) 
        REFERENCES METAR_REPORTS(REPORT_ID) ON DELETE CASCADE
);

CREATE SEQUENCE DUST_PHENOMENA_SEQ START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DUST_TYPE ON DUST_PHENOMENA(PHENOMENON_TYPE);
CREATE INDEX IDX_DUST_REPORT ON DUST_PHENOMENA(REPORT_ID);

-- =====================================================

-- 3️⃣ جدول المحطات
CREATE TABLE STATIONS (
    STATION_ID NUMBER PRIMARY KEY,
    STATION_CODE VARCHAR2(10) UNIQUE NOT NULL,
    STATION_NAME VARCHAR2(100),
    COUNTRY_CODE VARCHAR2(5),
    COUNTRY_NAME VARCHAR2(50),
    LATITUDE NUMBER(10,6),
    LONGITUDE NUMBER(10,6),
    ELEVATION NUMBER(10,2),
    ACTIVE_FLAG VARCHAR2(1) DEFAULT 'Y',
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE STATIONS_SEQ START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_STATION_CODE ON STATIONS(STATION_CODE);
CREATE INDEX IDX_STATION_COUNTRY ON STATIONS(COUNTRY_CODE);

-- =====================================================

-- 4️⃣ جدول الإحصائيات اليومية
CREATE TABLE DAILY_STATISTICS (
    STAT_ID NUMBER PRIMARY KEY,
    REPORT_DATE DATE NOT NULL,
    COUNTRY_CODE VARCHAR2(5) NOT NULL,
    TOTAL_REPORTS NUMBER DEFAULT 0,
    BLDU_COUNT NUMBER DEFAULT 0,
    BLSA_COUNT NUMBER DEFAULT 0,
    DU_COUNT NUMBER DEFAULT 0,
    SA_COUNT NUMBER DEFAULT 0,
    DS_COUNT NUMBER DEFAULT 0,
    SS_COUNT NUMBER DEFAULT 0,
    PO_COUNT NUMBER DEFAULT 0,
    MIN_VISIBILITY NUMBER(10,2),
    MAX_WIND_SPEED NUMBER(5,2),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_DAILY_STAT UNIQUE (REPORT_DATE, COUNTRY_CODE)
);

CREATE SEQUENCE DAILY_STATISTICS_SEQ START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DAILY_DATE ON DAILY_STATISTICS(REPORT_DATE);
CREATE INDEX IDX_DAILY_COUNTRY ON DAILY_STATISTICS(COUNTRY_CODE);

-- =====================================================
-- ✅ تم إنشاء جميع الجداول بنجاح!
-- =====================================================

-- اختبار الجداول
SELECT 'METAR_REPORTS created' AS status FROM DUAL WHERE EXISTS (SELECT 1 FROM USER_TABLES WHERE TABLE_NAME = 'METAR_REPORTS');
SELECT 'DUST_PHENOMENA created' AS status FROM DUAL WHERE EXISTS (SELECT 1 FROM USER_TABLES WHERE TABLE_NAME = 'DUST_PHENOMENA');
SELECT 'STATIONS created' AS status FROM DUAL WHERE EXISTS (SELECT 1 FROM USER_TABLES WHERE TABLE_NAME = 'STATIONS');
SELECT 'DAILY_STATISTICS created' AS status FROM DUAL WHERE EXISTS (SELECT 1 FROM USER_TABLES WHERE TABLE_NAME = 'DAILY_STATISTICS');
