-- =====================================================
-- Oracle APEX - النسخة المبسطة (بدون أي مشاكل)
-- =====================================================
-- قم بنسخ ولصق كل أمر على حدة في SQL Commands
-- =====================================================

-- الجدول الأول: METAR_REPORTS
CREATE TABLE METAR_REPORTS (
    REPORT_ID NUMBER,
    STATION_CODE VARCHAR2(10),
    OBSERVATION_TIME TIMESTAMP,
    LATITUDE NUMBER(10,6),
    LONGITUDE NUMBER(10,6),
    TEMPERATURE NUMBER(5,2),
    DEW_POINT NUMBER(5,2),
    WIND_DIRECTION NUMBER(3),
    WIND_SPEED NUMBER(5,2),
    VISIBILITY NUMBER(10,2),
    PRESSURE NUMBER(10,2),
    WEATHER_CODES VARCHAR2(100),
    RAW_METAR VARCHAR2(500),
    NETWORK VARCHAR2(20),
    COUNTRY_CODE VARCHAR2(5),
    CREATED_AT TIMESTAMP
);

-- Primary Key
ALTER TABLE METAR_REPORTS ADD CONSTRAINT PK_METAR_REPORTS PRIMARY KEY (REPORT_ID);

-- Unique Constraint
ALTER TABLE METAR_REPORTS ADD CONSTRAINT UK_METAR UNIQUE (STATION_CODE, OBSERVATION_TIME);

-- Not Null Constraints
ALTER TABLE METAR_REPORTS MODIFY STATION_CODE NOT NULL;
ALTER TABLE METAR_REPORTS MODIFY OBSERVATION_TIME NOT NULL;

-- Sequence
CREATE SEQUENCE METAR_REPORTS_SEQ START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_METAR_STATION ON METAR_REPORTS(STATION_CODE);
CREATE INDEX IDX_METAR_TIME ON METAR_REPORTS(OBSERVATION_TIME);
CREATE INDEX IDX_METAR_WEATHER ON METAR_REPORTS(WEATHER_CODES);
CREATE INDEX IDX_METAR_COUNTRY ON METAR_REPORTS(COUNTRY_CODE);

-- =====================================================
-- ✅ الجدول الأول تم بنجاح!
-- =====================================================

-- الجدول الثاني: DUST_PHENOMENA
CREATE TABLE DUST_PHENOMENA (
    PHENOMENON_ID NUMBER,
    REPORT_ID NUMBER,
    PHENOMENON_TYPE VARCHAR2(10),
    SEVERITY VARCHAR2(20),
    CREATED_AT TIMESTAMP
);

-- Primary Key
ALTER TABLE DUST_PHENOMENA ADD CONSTRAINT PK_DUST_PHENOMENA PRIMARY KEY (PHENOMENON_ID);

-- Foreign Key
ALTER TABLE DUST_PHENOMENA ADD CONSTRAINT FK_DUST_REPORT 
    FOREIGN KEY (REPORT_ID) REFERENCES METAR_REPORTS(REPORT_ID) ON DELETE CASCADE;

-- Not Null
ALTER TABLE DUST_PHENOMENA MODIFY REPORT_ID NOT NULL;
ALTER TABLE DUST_PHENOMENA MODIFY PHENOMENON_TYPE NOT NULL;

-- Sequence
CREATE SEQUENCE DUST_PHENOMENA_SEQ START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_DUST_TYPE ON DUST_PHENOMENA(PHENOMENON_TYPE);
CREATE INDEX IDX_DUST_REPORT ON DUST_PHENOMENA(REPORT_ID);

-- =====================================================
-- ✅ الجدول الثاني تم بنجاح!
-- =====================================================

-- الجدول الثالث: STATIONS
CREATE TABLE STATIONS (
    STATION_ID NUMBER,
    STATION_CODE VARCHAR2(10),
    STATION_NAME VARCHAR2(100),
    COUNTRY_CODE VARCHAR2(5),
    COUNTRY_NAME VARCHAR2(50),
    LATITUDE NUMBER(10,6),
    LONGITUDE NUMBER(10,6),
    ELEVATION NUMBER(10,2),
    ACTIVE_FLAG VARCHAR2(1),
    CREATED_AT TIMESTAMP
);

-- Primary Key
ALTER TABLE STATIONS ADD CONSTRAINT PK_STATIONS PRIMARY KEY (STATION_ID);

-- Unique
ALTER TABLE STATIONS ADD CONSTRAINT UK_STATION_CODE UNIQUE (STATION_CODE);

-- Not Null
ALTER TABLE STATIONS MODIFY STATION_CODE NOT NULL;

-- Sequence
CREATE SEQUENCE STATIONS_SEQ START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_STATION_CODE ON STATIONS(STATION_CODE);
CREATE INDEX IDX_STATION_COUNTRY ON STATIONS(COUNTRY_CODE);

-- =====================================================
-- ✅ الجدول الثالث تم بنجاح!
-- =====================================================

-- الجدول الرابع: DAILY_STATISTICS
CREATE TABLE DAILY_STATISTICS (
    STAT_ID NUMBER,
    REPORT_DATE DATE,
    COUNTRY_CODE VARCHAR2(5),
    TOTAL_REPORTS NUMBER,
    BLDU_COUNT NUMBER,
    BLSA_COUNT NUMBER,
    DU_COUNT NUMBER,
    SA_COUNT NUMBER,
    DS_COUNT NUMBER,
    SS_COUNT NUMBER,
    PO_COUNT NUMBER,
    MIN_VISIBILITY NUMBER(10,2),
    MAX_WIND_SPEED NUMBER(5,2),
    CREATED_AT TIMESTAMP
);

-- Primary Key
ALTER TABLE DAILY_STATISTICS ADD CONSTRAINT PK_DAILY_STATISTICS PRIMARY KEY (STAT_ID);

-- Unique
ALTER TABLE DAILY_STATISTICS ADD CONSTRAINT UK_DAILY_STAT UNIQUE (REPORT_DATE, COUNTRY_CODE);

-- Not Null
ALTER TABLE DAILY_STATISTICS MODIFY REPORT_DATE NOT NULL;
ALTER TABLE DAILY_STATISTICS MODIFY COUNTRY_CODE NOT NULL;

-- Sequence
CREATE SEQUENCE DAILY_STATISTICS_SEQ START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_DAILY_DATE ON DAILY_STATISTICS(REPORT_DATE);
CREATE INDEX IDX_DAILY_COUNTRY ON DAILY_STATISTICS(COUNTRY_CODE);

-- =====================================================
-- ✅ جميع الجداول تم إنشاؤها بنجاح!
-- =====================================================

-- اختبار
SELECT COUNT(*) AS METAR_COUNT FROM METAR_REPORTS;
SELECT COUNT(*) AS DUST_COUNT FROM DUST_PHENOMENA;
SELECT COUNT(*) AS STATION_COUNT FROM STATIONS;
SELECT COUNT(*) AS STAT_COUNT FROM DAILY_STATISTICS;
